---
title: "Merge data and export"
output:
  html_document:
    toc: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F)
library(tidyverse)
library(here)
library(ggplot2)
library(stringi)

theme_set(theme_bw())

# source(here("data_helpers.R"))
DATA_LOC=here("harmonized_data")
```

Set up the function for getting tables. 

```{r}
get_tbl <- function(con = DATA_LOC, dataset_name, tbl_name) {
  # con is fake rn, and takes in the root dir for all datasets
  if (missing(dataset_name)) {
    stop("dataset_name must be provided")
  }
  if (missing(tbl_name)) {
    stop("tbl_name must be provided")
  }
  
  file_path <- file.path(con, dataset_name, paste0(tbl_name, ".csv"))
  if (!file.exists(file_path)) {
    stop(paste("File does not exist:", file_path))
  }
  
  out <- read_csv(file_path, show_col_types = FALSE)
  
  if (tbl_name == "conditions") {
    out <- out |> 
      mutate(structure = structure |> 
               as.character() |> 
               replace_na("other") |> 
               factor(levels = c("thin", "medium", "med_thick", "thick", "network-swap", "naive-swap")) |> 
               fct_drop())
  }
  out
}
```


# Make tables


Mark with dataset IDs

```{r, eval=F}
# options to get trials / choices / messages for all datasets
dataset_names <- list.dirs(DATA_LOC, full.names = FALSE) |> 
  stri_remove_empty()
```



Messages

```{r}
messages <- map_df(dataset_names, \(d) get_tbl(DATA_LOC, d, "messages")) |> 
  rename(player_num = player_id)
```


Trials

```{r}
trials <-   map_df(dataset_names, \(d) get_tbl(DATA_LOC, d, "trials") |> 
                     mutate(target = as.character(target),
                            matchers = as.character(matchers))) |> 
  mutate(option_set = option_set |> 
           str_remove_all("\\[|\\]|\"") |> 
           str_replace_all(",", ";") )


```

Conditions & datasets

```{r}
conditions <- map_df(dataset_names, \(d) get_tbl(DATA_LOC, d, "conditions"))

datasets <- tibble(dataset_id = dataset_names) |>
  left_join(conditions |>
              select(dataset_id = paper_id, full_cite, short_cite) |>
              distinct()) 

conditions <- conditions |>
  rename(dataset_id = paper_id) |>
  select(dataset_id, condition_id, condition_label, group_size, structure, language) 
```


Choices

```{r}
choices <- map_df(dataset_names, function (d) {
  df <- get_tbl(DATA_LOC, d, "choices")  |>
    rename(player_num = player_id) |>
    mutate(player_num = as.numeric(player_num), 
           time_stamp = as.numeric(time_stamp),
           trial_id = as.numeric(trial_id),
           check_choices = as.numeric(check_choices)) |>
    select(-option_set)
  
  df
}) 
```


Write out for redivis with missing for NA to facilitate import. 

```{r}
write_csv(datasets, here("export", "datasets.csv"), na = "")
write_csv(messages, here("export", "messages.csv"), na = "")
write_csv(choices,  here("export", "choices.csv"), na = "")
write_csv(trials, here("export", "trials.csv"), na = "")
write_csv(conditions, here("export", "conditions.csv"), na = "")
```

